spring:
  messages:
    encoding: UTF-8
#  jpa:
#    generate-ddl: false
#    #    generate-ddl: true
#    hibernate:
#      ddl-auto: none
#  h2:
#    console:
#      enabled: true
#  datasource:
#      jdbc-url: h2:mem:mainDB
#      username: sa
#      password:
  sql:
    init:
      mode: always
      data-locations: classpath:data1sql
#      schema-locations: classpath:schema1.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    hidden-method:
      filter:
        enabled: true

logging:
  level:
    ROOT: ERROR